coverage:
  status:
    project:
      default:
        target: 80%        # Minimum threshold
        threshold: 0.1%    # Allowed drop before failing
        if_not_found: failure
        informational: false
    patch:
      default:
        target: 80%
        threshold: 0.1%
        if_not_found: fail
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

