on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-20.04
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/html-scipyorg/index.html
          circleci-jobs: build_docs
          job-title: build_doc artifact